In [9]:
import numpy as np #importation de la biblio numpy

num_etudiant = int(input("Donnez le nombre d'étubiants :")) #variable qui stocke le nombre d'étudiants
num_matiere = int(input("Donnez le nombre de matières :")) #variable qui stocke le nombre de matières

# création d'un tableau qui stocke la note de chaque étudiant dans chaque matière
note = np.zeros((num_etudiant, num_matiere), dtype = float)
print(note)

Donnez le nombre d'étubiants :5
Donnez le nombre de matières :5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
import numpy as np

# Step 2: Ask the user for the number of students and subjects
num_students = int(input("Enter the number of students: "))
num_subjects = int(input("Enter the number of subjects: "))

# Create a NumPy array to store marks (initialize with zeros)
marks = np.zeros((num_students, num_subjects), dtype=float)

# Step 4: Ask the user to enter the marks for each student in each subject
for i in range(num_students):
    print(f"Enter marks for student {i + 1}:")
    for j in range(num_subjects):
        marks[i][j] = float(input(f"Enter marks for subject {j + 1}: "))

# Step 5: Calculate total marks for each student
total_marks = np.sum(marks, axis=1)

# Step 6: Calculate the percentage for each student
percentage = (total_marks / (num_subjects * 100)) * 100

# Step 7: Calculate the grade for each student based on the grading system
grades = []
for percent in percentage:
    if percent >= 90:
        grades.append("A+")
    elif percent >= 80:
        grades.append("A")
5        grades.append("B+")
    elif percent >= 60:
        grades.append("B")
    elif percent >= 50:
        grades.append("C")
    else:
        grades.append("F")

# Step 8: Display the results in a tabular format
print("\nStudent\tTotal Marks\tPercentage\tGrade")
for i in range(num_students):
    print(f"Student {i + 1}\t{total_marks[i]}\t\t{percentage[i]:.2f}%\t\t{grades[i]}")


Enter the number of students: 2
Enter the number of subjects: 2
Enter marks for student 1:
Enter marks for subject 1: 50
Enter marks for subject 2: 70
Enter marks for student 2:
Enter marks for subject 1: 70
Enter marks for subject 2: 5

Student	Total Marks	Percentage	Grade
Student 1	120.0		60.00%		B
Student 2	75.0		37.50%		F


In [16]:
a = np.array([[1,2,3], [4,5,6]])
numbers = [1, 2, 3, 4, 5, 6]
print(len(a))
print(sum(numbers))
for i in range(len(a)):
    print(sum(a[i]))
print(sum(a))

2
21
6
15
[5 7 9]
